config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users, only: [:show, :new, :create]
  resources :trucks, only: [:index, :show, :new, :create]
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  resources :neighborhoods, only: [:index, :show, :new, :create]


  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'session'
  get 'signup', to: 'users#new', as: 'signup'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :trucks

end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :truck
  belongs_to :user

  validates :rating, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}
  validates :content, length: {minimum: 0, maximum: 700}
  validates :rating, presence: true



end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews
  belongs_to :neighborhood

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: {minimum: 2, maximum: 40}
  validates :specialty, length: {minimum: 2, maximum: 30}
  validates :specialty, presence: true

  def most_recent
    self.reviews = self.reviews.order(id: :desc)
  end

  def avg_rating
    total=0.0
    counter=0
    self.reviews.each_with_index do |review|
      total+=review.rating
      counter+=1
    end
    total/=counter
    total.round(2)
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews
  has_many :trucks, through: :reviews

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :name, length: {minimum: 2, maximum: 20}
  validates :email, length: {minimum: 5, maximum: 20}
  validates :password, length: {minimum: 3, maximum: 700}

  def most_recent
    self.reviews = self.reviews.order(id: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  before_action :logged_in?

  def current_user
    if session[:user_id]
      @curr_user = User.find(session[:user_id])
    end
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  def index
    @neighborhoods=Neighborhood.all
    render :index
  end

  def show
    @neighborhood=Neighborhood.find(params[:id])
    render :show
  end

  def new
    @neighborhood=Neighborhood.new
  end

  def create
    @neighborhood=Neighborhood.new(neighborhood_params)

    if @neighborhood.valid?
      @neighborhood.save
      redirect_to neighborhood_path(@neighborhood)
    else
      render :new
    end
  end

  private
  def neighborhood_params
    params.require(:neighborhood).permit(:name, :specialty)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorized


  def show
    @review=find_review
    render :show
  end

  def new
    @review=Review.new
  end

  def create
    @review=Review.new(user_id: @curr_user.id, truck_id: params[:review][:truck_id], content: params[:review][:content], rating: params[:review][:rating], image: params[:review][:image])
    if @review.valid?
      @review.save
      redirect_to user_path(@review.user)
    else
      redirect_to new_review_path
    end
  end

  def edit
    @review = find_review
  end

  def update
    @review = find_review
    @review.update(user_id: @curr_user.id, truck_id: params[:review][:truck_id], content: params[:review][:content], rating: params[:review][:rating], image: params[:review][:image])
    if @review.valid?
      redirect_to user_path(@curr_user)
    else
      render :edit
    end
  end

  def destroy
    @review = find_review
    @review.destroy
    redirect_to user_path(@curr_user)
  end


  private
  def review_params
    params.require(:review).permit(:content, :truck_id, :rating, :image)
  end

  def find_review
    review = Review.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in?, only: [:create, :new]

  def new
    # Login
    render :new
  end

  def create
    @curr_user = User.find_by(email: params[:email])
    # Does that curr_user exist? && does it match the authorization
    if @curr_user && @curr_user.authenticate(params[:password])
      # byebug
      session[:user_id] = @curr_user.id

      redirect_to user_path(@curr_user)
    else
      redirect_to login_path
    end
    # POST of the login
  end

  def destroy
    # Logging out
    session.delete :user_id

    redirect_to login_path
  end

  private
  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

  def index
    @trucks=Truck.all
    if params[:search]
      @trucks = Truck.search(params[:search]).order("created_at DESC")
    else
      @trucks = Truck.all.order("created_at DESC")
    end
    render :index
  end

  def show
    @truck=Truck.find(params[:id])
    render :show
  end

  def new
    @truck=Truck.new
  end

  def create
    @truck=Truck.new(truck_params)

    if @truck.valid?
      @truck.save
      redirect_to new_review_path
    else
      redirect_to new_truck_path
    end
  end


  private
  def truck_params
    params.require(:truck).permit(:name, :specialty, :neighborhood_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to login_path
    else
      redirect_to signup_path
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<%= render "partials/header" %>
<%= render "partials/navbar" %>
<%= yield %>

app/views/neighborhoods/index.html.erb
<h1 class="title">Pick a location! </h1>
  <ul>
    <%@neighborhoods.each do |neighborhood|  %>
      <li class="list">
          <%= link_to neighborhood.name, neighborhood_path(neighborhood) %>
      </li>
    <% end  %>
  </ul>

app/views/neighborhoods/new.html.erb
<%= form_for @neighborhood do |f| %>
<br>
<%= f.label :name %>
<br>
<br>
<%= f.text_field :name %>
<br>
<br>

<%= f.submit  %>
<% end %>

app/views/neighborhoods/show.html.erb
<h1 class="title" ><%= @neighborhood.name %></h1>

  <ul>
    <% @neighborhood.trucks.each do |truck| %>
    <li class="list"><%= link_to truck.name, truck_path(truck) %></li>
    <%end  %>
  </ul>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomads</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

app/views/partials/_navbar.html.erb
<body>

  <ul class="nav-bar">
    <li class= "nav-bar-items"><a href="/">Home</a></li>
    <li class= "nav-bar-items"> <%= link_to "Trucks", trucks_path %>  </li>
    <li class= "nav-bar-items">  <%= link_to "Neighborhoods", neighborhoods_path %>  </li>

    <div class="search">
      <span>
      <%= form_tag(trucks_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Trucks", size:"100", maxlength: "40" %>
      <%= submit_tag "Search", :name => nil, class: "submit"%>
      <% end %></span>
    </div>


    <% if logged_in? %>
    <li class= "nav-bar-items" style="float:right">  <%= link_to "Logout", logout_path, method: :delete %>  </li>
    <li class="nav-bar-items" style="float:right; text-transform:capitalize" > <%= link_to @curr_user.name, user_path(@curr_user) %> </li>
    <% else %>
    <li class= "nav-bar-items" style="float:right">  <%= link_to "Login", login_path %>  </li>
    <li class= "nav-bar-items" style="float:right">  <%= link_to "Sign Up", signup_path %>  </li>
    <% end %>
  </ul>

</body>

app/views/reviews/edit.html.erb
<h1 class="title">Edit Review </h1>
<div class="signin">


<%= form_for @review, method: :patch do |f| %>
<br>
<%= f.label :truck %>
<br>
<%= f.collection_select :truck_id, Truck.all, :id, :name, prompt: "Select a truck"%>
<br>
  <i> "Don't see your truck? Click here to add a new truck.</i>
<br>
<%= link_to '<button type ="button"> New Truck</button>'.html_safe, new_truck_path %>
<br>
<%= f.label :rating %>
<br>
<%= f.number_field :rating, placeholder: "1-5", min: 1, max: 5 , class: "formlabel"%>
<br>
<%= f.label :content %>
<br>
<%= f.text_area :content, size: "60x12", placeholder: "What do you want to say?", class: "formlabel" %>
<br>
<br>
<%= f.file_field :image %>
<br>
<br>
<%= f.submit "Post", class: "submit" %>
<% end %>
</div>

app/views/reviews/new.html.erb
<h1 class="title">Review Form </h1>
<div class="signin">


<%= form_for @review do |f| %>
<br>
<%= f.label :truck %>
<br>
<%= f.collection_select :truck_id, Truck.all, :id, :name, prompt: "Select a truck"%>
<br>
  <i> "Don't see your truck? Click here to add a new truck.</i>
<br>
<%= link_to '<button type ="button"> New Truck</button>'.html_safe, new_truck_path %>
<br>
<%= f.label :rating %>
<br>
<%= f.number_field :rating, placeholder: "1-5", min: 1, max: 5 , class: "formlabel"%>
<br>
<%= f.label :content %>
<br>
<%= f.text_area :content, size: "60x12", placeholder: "What do you want to say?", class: "formlabel" %>
<br>
<br>
<%= f.file_field :image %>
<br>
<br>
<%= f.submit "Post", class: "submit" %>
<% end %>
</div>

app/views/trucks/index.html.erb
<h1 class="title">All Food Trucks! </h1>
  <ul>
    <% if @trucks.blank? %>
      <h4>There are no trucks containing the term <%= params[:search] %>.</h4>
    <% end %>
    <%@trucks.each do |truck|  %>
    <li class="list">
      <%= link_to truck.name, truck_path(truck) %>
    </li>
    <% end  %>
  </ul>

app/views/trucks/new.html.erb
<h1 class="title"> New Food Truck Form  </h1>

<div class="signin">


<%= form_for @truck do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :specialty %>
  <br>
  <%= f.text_field :specialty %>
  <br><br>
  <%= f.label "Neighborhood" %>
  <br><br>
  <%= f.collection_select :neighborhood_id, Neighborhood.all, :id, :name, prompt: "Select one"%>
  <br>
  <br>
  <br>
  <%= f.submit "Create Truck",  class:"submit"%>

<% end %>
</div>

app/views/trucks/show.html.erb
<h1 class="title"><%= @truck.name %> </h1>
<br>
<h3 class="titletoo">Specializes in <%= @truck.specialty %></h3>
<div class="grid-container-too">
  <div class="grid-item-too">
    <h2  class="titletoo", style: "font-size:30px">Find us in <%=link_to @truck.neighborhood.name, neighborhood_path(@truck.neighborhood), class:"titletoo"%>!</h2>
  </div>
  <div class="grid-item-too">
    <h2  class="titletoo", style: "font-size:30px"> <%= link_to "Review Us!", new_review_path , class:"titletoo"%></h2>
  </div>
  <div class="grid-item-too">
    <h1 class="average_rating">Rating: <%= @truck.avg_rating %></h1>
  </div>
</div>

<div class="grid-container">
  <%@truck.most_recent.each do |review|  %>
    <div class="grid-item">
      Written By:
      <%= link_to review.user.name, user_path(review.user) %>
      <br>
      <br>
      Rating:

      <br>
      <div class="rating">
        <%= review.rating %>
      </div>

    </div>

    <div class="grid-item">
      <%= review.content %>
    </div>

    <div class="grid-item">
        <%= image_tag (review.image.url) if review.image? %>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="title">Sign Up!</h1>
<div class="signin">


<%= form_for @user do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name, class: "formlabel"%>
  <br>
  <br>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.email_field :email, class: "formlabel" %>
  <br>
  <br>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password,class: "formlabel" %>
  <br>
  <br>
  <br>
  <%= f.label :password_confirmation %>
  <br>
  <%= f.password_field :password_confirmation,  class: "formlabel"%>
  <br>
  <br>
  <br>

  <%= f.submit  "Sign Up", class:"submit"%>
<% end %>
</div>

app/views/users/show.html.erb
 <h1 class="title"><%= @user.name %></h1>
 <div class="link">
    <%= link_to "Create A New Review", new_review_path %>
 </div>

  <h2 class="titletoo">My Reviews</h2>
  <div class="grid-container">
  <% @user.most_recent.each do |review| %>
    <div class="grid-item">
      <h2><%= link_to review.truck.name, truck_path(review.truck) %></h2>
      <br>
      My rating:
      <br>
      <div class="rating">
          <%= review.rating%>
      </div>
      <br>
      <br>
      <% if @curr_user == @user %>
        <%= link_to "Edit", edit_review_path(review)%>
        <%= link_to "Delete", review_path(review), :data => {:confirm => "You sure dawg?", :method => "delete"} %>
      <% end %>
    </div>

    <div class="grid-item">
      <%= review.content %>
    </div>

    <div class="grid-item">
        <%= image_tag (review.image.url) if review.image? %>
    </div>
    <% end %>
</div>


</ul>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Nomads</title>
  </head>
  <body>
    <br>
    <!-- <h1 class="title">Nomads</h1> -->
    <%= image_tag asset_path("nomad1.jpg"), class: "logoimage" %>
    <h2 class="titletoo">Travel Like a Nomad. Eat Like a Nomad. </h2>
    <br>
    <%= image_tag asset_path("foodtruck.jpg"), class: "centerimage" %>

    <h2 class="movingdesc">Source For All Your Food Truck Needs</h2>
    <br>

    <!-- <div class="titletoo">
      <%= form_tag(trucks_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Trucks" %>
      <%= submit_tag "Search", :name => nil, class:"submit" %>
      <% end %>

    </div> -->





  </body>
</html>